// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC9HMIuKQQO9yj5AZy-Aeycs2HgeKObNg',
    appId: '1:775001795217:web:0a21ad90c771d17858ad30',
    messagingSenderId: '775001795217',
    projectId: 'fbnote-924f8',
    authDomain: 'fbnote-924f8.firebaseapp.com',
    storageBucket: 'fbnote-924f8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV-qwl1MEkFxwnMMOLIflfXcCfTS4iUKs',
    appId: '1:775001795217:android:0a02fda592318b2058ad30',
    messagingSenderId: '775001795217',
    projectId: 'fbnote-924f8',
    storageBucket: 'fbnote-924f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8u-6HBVzHRxIftqe4zU1oQ4pmKKkRbuQ',
    appId: '1:775001795217:ios:826de50a5920a19058ad30',
    messagingSenderId: '775001795217',
    projectId: 'fbnote-924f8',
    storageBucket: 'fbnote-924f8.firebasestorage.app',
    iosClientId: '775001795217-kjflqtiuj26ui1okppsaokn6j48ac3j3.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8u-6HBVzHRxIftqe4zU1oQ4pmKKkRbuQ',
    appId: '1:775001795217:ios:826de50a5920a19058ad30',
    messagingSenderId: '775001795217',
    projectId: 'fbnote-924f8',
    storageBucket: 'fbnote-924f8.firebasestorage.app',
    iosClientId: '775001795217-kjflqtiuj26ui1okppsaokn6j48ac3j3.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesAppFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCC9HMIuKQQO9yj5AZy-Aeycs2HgeKObNg',
    appId: '1:775001795217:web:e5a12cd70feddb9b58ad30',
    messagingSenderId: '775001795217',
    projectId: 'fbnote-924f8',
    authDomain: 'fbnote-924f8.firebaseapp.com',
    storageBucket: 'fbnote-924f8.firebasestorage.app',
  );
}
